context("basic functionality")
test_that("we can do something", {
  skip_on_cran()
  expect_that(agd_ipt(), is_a("data.frame"))
  expect_that(geographic_spread(), is_a("data.frame"))
  expect_that(surveillance_areas(), is_a("data.frame"))
  expect_that(hospitalizations("flusurv"), is_a("data.frame"))
  expect_that(hospitalizations("eip"), is_a("data.frame"))
  expect_that(hospitalizations("eip", "Colorado"), is_a("data.frame"))
  expect_that(hospitalizations("ihsp"), is_a("data.frame"))
  expect_that(hospitalizations("ihsp", "Oklahoma"), is_a("data.frame"))
  expect_that(ilinet("national"), is_a("data.frame"))
  expect_that(ilinet("hhs"), is_a("data.frame"))
  expect_that(ilinet("census"), is_a("data.frame"))
  expect_that(ilinet("state"), is_a("data.frame"))
  expect_that(ili_weekly_activity_indicators(2017), is_a("data.frame"))
  expect_that(pi_mortality("national"), is_a("data.frame"))
  expect_that(pi_mortality("state"), is_a("data.frame"))
  expect_that(pi_mortality("region"), is_a("data.frame"))
  expect_that(state_data_providers(), is_a("data.frame"))
  expect_that(who_nrevss("national"), is_a("list"))
  expect_that(who_nrevss("hhs"), is_a("list"))
  expect_that(who_nrevss("census"), is_a("list"))
  expect_that(who_nrevss("state"), is_a("list"))
  expect_that(cdc_coverage_map(), is_a("sf"))
})
